### ISSUE TITLE
Should the auto_reload helper only be declared if in development mode?

### ISSUE THREAD

**Issue by srchulo** [preaction/Mojolicious-Plugin-AutoReload#4]
Currently the auto_reload websocket and after_render hook are only added when in development mode. However, the auto_reload helper is always loaded. Should this also only be loaded in development mode?

**Comment by preaction** [comment]
No, otherwise it would cause an exception if the user had the `auto_reload` helper in their template (to control where the script goes). It doesn't do anything unless the mode is `development`, so it's safe to keep around.

**Comment by srchulo** [comment]
Ah, that's my mistake for not reading the documentation closely enough and just applying it to how I was using it. Thanks for the response! I'll go ahead and close.
